name: dependency-audit
on: [push,pull_request]
permissions: {contents: read}
jobs:
 scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
  - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
    with: {scan-type: fs, scan-ref: ., exit-code: "1", ignore-unfixed: true}
  - uses: anchore/sbom-action@66cbf4bc1f1c0d2edc94016e65bc221b6bb0ad6c
    with: {path: ., format: cyclonedx-json, output-file: sbom.cdx.json}
