name: dependency-audit
on: [push,pull_request]
permissions: {contents: read}
jobs:
 scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
  - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
    with: {scan-type: fs, scan-ref: ., exit-code: "1", ignore-unfixed: true}
  - uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26
    with: {path: ., format: cyclonedx-json, output-file: sbom.cdx.json}
